FROM bitwalker/alpine-erlang:6.1

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ docker libpcap && \
    rm -rf /var/cache/apk/*

EXPOSE 9100
ENV PORT=9100 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD docker_traffic_counter.tar.gz ./
RUN chown -R default ./releases

USER default

ENTRYPOINT ["/opt/app/bin/docker_traffic_counter"]
CMD ["foreground"]
